import { Poor_Story } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";

const poorStory = Poor_Story({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata = {
  title: "My-SPD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      
      <body className={poorStory.className}>
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
      />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
